=== mjones3/interface-exception-collector-service/backend/partnerorderprovider/src/main/resources/interface-schema/Modify-Order-Inbound-1.0.0.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "Modify Order inbound",
  "description": "Modify a customer order",
  "type": "object",
  "properties": {
    "locationCode": {
      "$ref": "#/definitions/locationCode"
    },
    "modifyReason": {
      "type": "string",
      "title": "Modification Reason",
      "minLength": 1,
      "maxLength": 250
    },
    "modifyEmployeeCode": {
      "type": "string",
      "title": "Modify Employee Code",
      "maxLength": 50
    },
    "modifyDate": {
      "$ref": "#/definitions/dateTimePattern"
    },
    "shipmentType": {
      "type": "string",
      "enum": [
        "CUSTOMER"
      ]
    },
    "deliveryType": {
      "type": "string" ,
      "enum": [
        "DATE_TIME",
        "SCHEDULED",
        "STAT",
        "ROUTINE",
        "ASAP"
      ]
    },
    "orderPickType": {
      "$ref": "#/definitions/orderPickType"
    },
    "shippingMethod": {
      "$ref": "#/definitions/shippingMethod"
    },
    "productCategory": {
      "$ref": "#/definitions/productCategory"
    },
    "desiredShippingDate": {
      "$ref": "#/definitions/datePattern"
    },
    "comments": {
      "$ref": "#/definitions/comments"
    },
    "orderItems": {
      "$ref": "#/definitions/orderItems"
    }
  },
  "required": [
    "locationCode",
    "modifyEmployeeCode",
    "modifyReason",
    "productCategory",
    "modifyDate",
    "orderItems"
  ],
  "additionalProperties": false,
  "definitions": {
    "locationCode": {
      "type": "string",
      "title": "location code",
      "minLength": 1,
      "maxLength": 255
    },
    "modifyEmployeeCode": {
      "type": "string",
      "title": "Modify Employee Code",
      "minLength": 1,
      "maxLength": 50
    },
    "datePattern": {
      "type": ["string","null"],
      "pattern": "^(\\d{4}-\\d{2}-\\d{2})$"
    },
    "dateTimePattern": {
      "type": "string",
      "pattern": "^(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})$"
    },
    "orderPickType": {
      "type": "object",
      "title": "Order pickup type",
      "properties": {
        "willCallPickUp": {
          "$ref": "#/definitions/orderPickType.willCallPickUp"
        },
        "phoneNumber": {
          "$ref": "#/definitions/orderPickType.phoneNumber"
        }
      },
      "additionalProperties": false
    },
    "orderPickType.willCallPickUp": {
      "type": "boolean"
    },
    "orderPickType.phoneNumber": {
      "type": "string"
    },
    "productCategory": {
      "type": "string",
      "minLength": 1,
      "title": "Ordered product category"

    },
    "shippingMethod": {
      "type": "string",
      "title": "Shipping method used for shipment"

    },
    "comments": {
      "type": "string",
      "title": "Comment associated to the order",
      "maxLength": 1000
    },
    "orderItems": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/orderItems.item"
      }
    },
    "orderItems.item": {
      "type": "object",
      "properties": {
        "productFamily": {
          "$ref": "#/definitions/orderItems.productFamily"
        },
        "bloodType": {
          "$ref": "#/definitions/orderItems.bloodType"
        },
        "quantity": {
          "$ref": "#/definitions/orderItems.quantity"
        },
        "comments": {
          "$ref": "#/definitions/orderItems.comments"
        }
      },
      "required": [
        "productFamily",
		    "bloodType",
        "quantity"
      ],
      "additionalProperties": false
    },
    "orderItems.productFamily": {
      "type": "string",
	  "minLength": 1,
      "title": "Ordered product family"
    },
    "orderItems.bloodType": {
      "type": "string",
	  "minLength": 1,
      "title": "Ordered product blood group description"
    },
    "orderItems.quantity": {
      "type": "integer",
      "title": "Ordered product quantity"
    },
    "orderItems.comments": {
      "type": "string",
      "title": "Comments associated with the ordered product, if any",
      "maxLength": 1000
    }
  }
}

=== mjones3/interface-exception-collector-service/backend/partnerorderprovider/src/test/resources/inbound-test-files/modify-order-inbound-scenario-dis-325-will_pick_up_false_no_phone.json
{
  "locationCode": "123456789",
  "modifyDate": "2023-04-25 20:09:01",
  "modifyEmployeeCode": "ee1bf88e-2137-4a17-835a-d43e7b738374",
  "modifyReason":"Missing Product details.",
  "deliveryType": "SCHEDULED",
  "orderPickType": {
    "willCallPickUp": false
  },
  "shippingMethod": "FEDEX",
  "productCategory": "FROZEN",
  "desiredShippingDate": "2020-04-25",
  "comments": "string",
  "orderItems": [
    {
      "productFamily": "PLASMA_TRANSFUSABLE",
      "bloodType": "AB",
      "quantity": 1,
      "comments": "Comments"
    }
  ]
}
