=== mjones3/interface-exception-collector-service/backend/partnerorderprovider/src/main/resources/interface-schema/Order-Management-Inbound-1.0.0.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "Order management-inbound",
  "description": "Create customer order",
  "type": "object",
  "properties": {
    "externalId": {
      "$ref": "#/definitions/externalId"
    },
    "orderStatus": {
      "type": "string",
      "enum": [
        "OPEN"
      ]
    },
    "locationCode": {
      "$ref": "#/definitions/locationCode"
    },
    "createDate": {
      "$ref": "#/definitions/dateTimePattern"
    },
    "createEmployeeCode": {
      "type": "string"
    },
    "shipmentType": {
      "type": "string",
      "enum": [
        "CUSTOMER"
      ]
    },
    "deliveryType": {
      "type": "string" ,
      "enum": [
        "DATE_TIME",
        "SCHEDULED",
        "STAT",
        "ROUTINE",
        "ASAP"
      ]
    },
    "orderPickType": {
      "$ref": "#/definitions/orderPickType"
    },
    "shippingMethod": {
      "$ref": "#/definitions/shippingMethod"
    },
    "productCategory": {
      "$ref": "#/definitions/productCategory"
    },
    "desiredShippingDate": {
      "$ref": "#/definitions/datePattern"
    },
    "shippingCustomerCode": {
      "$ref": "#/definitions/shippingCustomerCode"
    },
    "billingCustomerCode": {
      "$ref": "#/definitions/billingCustomerCode"
    },
    "comments": {
      "$ref": "#/definitions/comments"
    },
    "orderItems": {
      "$ref": "#/definitions/orderItems"
    }
  },
  "required": [
    "externalId",
    "orderStatus",
    "locationCode",
    "shipmentType",
    "productCategory",
    "orderItems"
  ],
  "additionalProperties": false,
  "definitions": {
    "externalId": {
      "type": "string",
      "title": "ExternalId of the order",
      "minLength": 1,
      "maxLength": 255
    },
    "locationCode": {
      "type": "string",
      "title": "location code",
      "minLength": 1,
      "maxLength": 255
    },
    "datePattern": {
      "type": ["string","null"],
      "pattern": "^(\\d{4}-\\d{2}-\\d{2})$"
    },
    "dateTimePattern": {
      "type": ["string","null"],
      "pattern": "^(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})$"
    },
    "orderPickType": {
      "type": "object",
      "title": "Order pickup type",
      "properties": {
        "willCallPickUp": {
          "$ref": "#/definitions/orderPickType.willCallPickUp"
        },
        "phoneNumber": {
          "$ref": "#/definitions/orderPickType.phoneNumber"
        }
      },
      "additionalProperties": false
    },
    "orderPickType.willCallPickUp": {
      "type": "boolean"
    },
    "orderPickType.phoneNumber": {
      "type": "string"
    },
    "productCategory": {
      "type": "string",
      "minLength": 1,
      "title": "Ordered product category"

    },
    "shippingMethod": {
      "type": "string",
      "title": "Shipping method used for shipment"

    },
    "shippingCustomerCode": {
      "type": "string",
      "title": "Shipping Customer Code of ordering hospital"
    },
    "billingCustomerCode": {
      "type": "string",
      "title": "Billing Customer Code of ordering hospital"
    },
    "comments": {
      "type": "string",
      "title": "Comment associated to the order"
    },
    "orderItems": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/orderItems.item"
      }
    },
    "orderItems.item": {
      "type": "object",
      "properties": {
        "productFamily": {
          "$ref": "#/definitions/orderItems.productFamily"
        },
        "bloodType": {
          "$ref": "#/definitions/orderItems.bloodType"
        },
        "quantity": {
          "$ref": "#/definitions/orderItems.quantity"
        },
        "comments": {
          "$ref": "#/definitions/orderItems.comments"
        }
      },
      "required": [
        "productFamily",
		    "bloodType",
        "quantity"
      ],
      "additionalProperties": false
    },
    "orderItems.productFamily": {
      "type": "string",
	  "minLength": 1,
      "title": "Ordered product family"
    },
    "orderItems.bloodType": {
      "type": "string",
	  "minLength": 1,
      "title": "Ordered product blood group description"
    },
    "orderItems.quantity": {
      "type": "integer",
      "title": "Ordered product quantity"
    },
    "orderItems.comments": {
      "type": "string",
      "title": "Comments associated with the ordered product, if any"
    }
  }
}

=== mjones3/interface-exception-collector-service/backend/partnerorderprovider/src/test/resources/inbound-test-files/order-inbound-scenario-rbc-path.json
{
  "externalId": "114117922233599",
  "orderStatus": "OPEN",
  "locationCode": "123456789",
  "createDate": "2023-04-25 20:09:01",
  "createEmployeeCode": "ee1bf88e-2137-4a17-835a-d43e7b738374",
  "shipmentType": "CUSTOMER",
  "deliveryType": "SCHEDULED",
  "orderPickType": {
    "willCallPickUp": true,
    "phoneNumber": "987654321"
  },
  "shippingMethod": "FEDEX",
  "productCategory": "REFRIGERATED",
  "desiredShippingDate": "2025-12-31",
  "shippingCustomerCode": "99741",
  "billingCustomerCode": "99741",
  "comments": "Red Blood Cells for A+",
  "orderItems": [
    {
      "productFamily": "RED_BLOOD_CELLS",
      "bloodType": "AP",
      "quantity": 1,
      "comments": "Comments"
    }
  ]
}

=== mjones3/interface-exception-collector-service/backend/partnerorderprovider/src/test/resources/inbound-test-files/order-inbound-scenario-dis-322-create_date_null.json
{
  "externalId": "114117922233598",
  "orderStatus": "OPEN",
  "locationCode": "123456789",
  "createDate": null,
  "createEmployeeCode": "ee1bf88e-2137-4a17-835a-d43e7b738374",
  "shipmentType": "CUSTOMER",
  "deliveryType": "SCHEDULED",
  "orderPickType": {
    "willCallPickUp": true,
    "phoneNumber": "12333333"
  },
  "shippingMethod": "FEDEX",
  "productCategory": "FROZEN",
  "desiredShippingDate": "2020-04-25",
  "shippingCustomerCode": "99741",
  "billingCustomerCode": "99741",
  "comments": "string",
  "orderItems": [
    {
      "productFamily": "PLASMA_TRANSFUSABLE",
      "bloodType": "AB",
      "quantity": 1,
      "comments": "Comments"
    }
  ]
}

=== mjones3/interface-exception-collector-service/backend/partnerorderprovider/src/test/resources/inbound-test-files/order-inbound-scenario-dis-323-create_employee_code_no_field.json
{
  "externalId": "114117922233598",
  "orderStatus": "OPEN",
  "locationCode": "123456789",
  "createDate": "2023-04-25 20:09:01",
  "shipmentType": "CUSTOMER",
  "deliveryType": "SCHEDULED",
  "orderPickType": {
    "willCallPickUp": true,
    "phoneNumber": "12333333"
  },
  "shippingMethod": "FEDEX",
  "productCategory": "FROZEN",
  "desiredShippingDate": "2020-04-25",
  "shippingCustomerCode": "99741",
  "billingCustomerCode": "99741",
  "comments": "string",
  "orderItems": [
    {
      "productFamily": "PLASMA_TRANSFUSABLE",
      "bloodType": "AB",
      "quantity": 1,
      "comments": "Comments"
    }
  ]
}

=== mjones3/interface-exception-collector-service/backend/partnerorderprovider/src/test/resources/inbound-test-files/order-inbound-scenario-whole-blood-leukoreduced-path.json
{
  "externalId": "114117922233600",
  "orderStatus": "OPEN",
  "locationCode": "123456789",
  "createDate": "2023-04-25 20:09:01",
  "createEmployeeCode": "ee1bf88e-2137-4a17-835a-d43e7b738374",
  "shipmentType": "CUSTOMER",
  "deliveryType": "SCHEDULED",
  "orderPickType": {
    "willCallPickUp": true,
    "phoneNumber": "987654321"
  },
  "shippingMethod": "FEDEX",
  "productCategory": "REFRIGERATED",
  "desiredShippingDate": "2025-12-31",
  "shippingCustomerCode": "99741",
  "billingCustomerCode": "99741",
  "comments": "Whole Blood Leukoreduced for A+",
  "orderItems": [
    {
      "productFamily": "WHOLE_BLOOD_LEUKOREDUCED",
      "bloodType": "AP",
      "quantity": 1,
      "comments": "Comments"
    }
  ]
}

=== mjones3/interface-exception-collector-service/backend/partnerorderprovider/src/test/resources/inbound-test-files/order-inbound-scenario-whole-blood-path.json
{
  "externalId": "114117922233601",
  "orderStatus": "OPEN",
  "locationCode": "123456789",
  "createDate": "2023-04-25 20:09:01",
  "createEmployeeCode": "ee1bf88e-2137-4a17-835a-d43e7b738374",
  "shipmentType": "CUSTOMER",
  "deliveryType": "SCHEDULED",
  "orderPickType": {
    "willCallPickUp": true,
    "phoneNumber": "987654321"
  },
  "shippingMethod": "FEDEX",
  "productCategory": "REFRIGERATED",
  "desiredShippingDate": "2025-12-31",
  "shippingCustomerCode": "99741",
  "billingCustomerCode": "99741",
  "comments": "Whole Blood for A+",
  "orderItems": [
    {
      "productFamily": "WHOLE_BLOOD",
      "bloodType": "AP",
      "quantity": 1,
      "comments": "Comments"
    }
  ]
}
