=== mjones3/interface-exception-collector-service/backend/eventbridge/src/main/resources/schema/order-cancelled-outbound.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "eventId": {
      "type": "string"
    },
    "occurredOn": {
      "type": "string"
    },
    "eventVersion": {
      "type": "string"
    },
    "eventType": {
      "type": "string"
    },
    "payload": {
      "type": "object",
      "properties": {
        "orderNumber": {
          "type": "integer"
        },
        "externalId": {
          "type": "string"
        },
        "orderStatus": {
          "type": "string"
        },
        "locationCode": {
          "type": "string"
        },
        "createDate": {
          "type": "string"
        },
        "createEmployeeCode": {
          "type": "string"
        },
        "shipmentType": {
          "type": "string"
        },
        "priority": {
          "type": "string"
        },
        "shippingMethod": {
          "type": "string"
        },
        "productCategory": {
          "type": "string"
        },
        "desiredShippingDate": {
          "type": ["null","string"]
        },
        "shippingCustomerCode": {
          "type": "string"
        },
        "billingCustomerCode": {
          "type": "string"
        },
        "comments": {
          "type": ["null","string"]
        },
        "willPickUp": {
          "type": "boolean"
        },
        "willPickUpPhoneNumber": {
          "type": ["null","string"]
        },
        "totalShipped": {
          "type": ["null","integer"]
        },
        "totalRemaining": {
          "type": ["null","integer"]
        },
        "totalProducts": {
          "type": ["null","integer"]
        },
        "orderItems": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "productFamily": {
                  "type": "string"
                },
                "bloodType": {
                  "type": "string"
                },
                "quantity": {
                  "type": "integer"
                },
                "quantityShipped": {
                  "type": "integer"
                },
                "quantityRemaining": {
                  "type": "integer"
                },
                "comments": {
                  "type": ["null","string"]
                }
              },
              "required": [
                "productFamily",
                "bloodType",
                "quantity",
                "quantityShipped",
                "quantityRemaining"
              ]
            }
          ]
        },
        "cancelEmployeeId": {
          "type": "string"
        },
        "cancelDate": {
          "type": "string"
        },
        "cancelReason": {
          "type": "string"
        },
        "transactionId": {
          "type": ["null","string"]
        }
      },
      "required": [
        "orderNumber",
        "externalId",
        "orderStatus",
        "locationCode",
        "createDate",
        "createEmployeeCode",
        "shipmentType",
        "priority",
        "shippingMethod",
        "productCategory",
        "shippingCustomerCode",
        "billingCustomerCode",
        "willPickUp",
        "orderItems",
        "cancelEmployeeId",
        "cancelDate",
        "cancelReason"
      ]
    }
  },
  "required": [
    "eventId",
    "occurredOn",
    "payload",
    "eventType",
    "eventVersion"
  ]
}

=== mjones3/interface-exception-collector-service/backend/eventbridge/src/test/resources/order-cancelled-event.json
{
  "eventId": "1ddb5b6a-0873-4b91-bcf4-7d3ec83e6de1",
  "occurredOn": "2025-06-23T13:03:28.589922092Z",
  "payload": {
    "orderNumber": 1,
    "externalId": "EXTDIS3150001",
    "orderStatus": "CANCELLED",
    "locationCode": "123456789",
    "createDate": "2025-06-23T03:00:00Z",
    "createEmployeeCode": "ee1bf88e-2137-4a17-835a-d43e7b738374",
    "shipmentType": "CUSTOMER",
    "priority": "SCHEDULED",
    "shippingMethod": "FEDEX",
    "productCategory": "FROZEN",
    "desiredShippingDate": "2026-12-25",
    "shippingCustomerCode": "A1235",
    "billingCustomerCode": "A1235",
    "comments": null,
    "willPickUp": false,
    "willPickUpPhoneNumber": null,
    "totalShipped": 0,
    "totalRemaining": 10,
    "totalProducts": 10,
    "orderItems": [
      {
        "productFamily": "PLASMA_TRANSFUSABLE",
        "bloodType": "A",
        "quantity": 10,
        "quantityShipped": 0,
        "quantityRemaining": 10,
        "comments": "Comments"
      }
    ],
    "cancelEmployeeId": "ee1bf88e-2137-4a17-835a-d43e7b738374",
    "cancelDate": "2025-06-23T13:03:28.204237158Z",
    "cancelReason": "Customer no longer need",
    "transactionId": "df7092f3-78a6-4d17-ae2c-e9de07db6f3c"
  },
  "eventType": "OrderCancelled",
  "eventVersion": "1.0"
}
