=== mjones3/interface-exception-collector-service/backend/eventbridge/src/main/resources/schema/recovered-plasma-shipment-closed.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "eventId": {
      "type": "string"
    },
    "occurredOn": {
      "type": "string"
    },
    "eventVersion": {
      "type": "string"
    },
    "eventType": {
      "type": "string"
    },

    "payload": {
      "type": "object",
      "properties": {
        "shipmentNumber": {
          "type": "string"
        },
        "locationCode": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "createEmployeeId": {
          "type": "string"
        },
        "productType": {
          "type": "string"
        },
        "transportationReferenceNumber": {
          "type": ["string","null"]
        },
        "shipmentDate": {
          "type": ["string","null"]
        },
        "cartonTareWeight": {
          "type": ["number","null"]
        },
        "createDate": {
          "type": "string"
        },
        "modificationDate": {
          "type": "string"
        },
        "closedEmployeeId": {
          "type": "string"
        },
        "closeDate": {
          "type": "string"
        },
        "customerCode": {
          "type": "string"
        },
        "customerName": {
          "type": "string"
        },
        "customerState": {
          "type": "string"
        },
        "customerPostalCode": {
          "type": "string"
        },
        "customerCountry":{
          "type": "string"
        },
        "customerCountryCode":{
          "type": "string"
        },
        "customerCity": {
          "type": "string"
        },
        "customerDistrict": {
          "type": ["string","null"]
        },
        "customerAddressLine1": {
          "type": "string"
        },
        "customerAddressLine2": {
          "type": ["string","null"]
        },
        "customerAddressContactName": {
          "type": ["string","null"]
        },
        "customerAddressPhoneNumber":{
          "type": ["string","null"]
        },
        "customerAddressDepartmentName": {
          "type": ["string","null"]
        },
        "totalCartons": {
          "type": "integer"
        },
        "locationShipmentCode": {
          "type": "string"
        },
        "locationCartonCode":  {
          "type": "string"
        },
        "cartonList": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
              "cartonNumber": {
                "type": "string"
              },
              "locationCode": {
                "type": "string"
              },
              "cartonSequence": {
                "type": "integer"
              },
              "closeEmployeeId": {
                "type": "string"
              },
              "closeDate": {
                "type": "string"
              },
              "productType": {
                "type": "string"
              },
              "status": {
                "type": "string"
              },
              "totalProducts": {
                "type": "integer"
              },
              "totalWeight": {
                "type": "number"
              },
              "totalVolume": {
                "type": "number"
              },
                "packedProducts": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {

                      "unitNumber":  {
                        "type": "string"
                      },
                      "productCode":  {
                        "type": "string"
                      },
                      "packedByEmployeeId":  {
                        "type": "string"
                      },
                      "productType":  {
                        "type": "string"
                      },
                      "volume":  {
                        "type": ["number","null"]
                      },
                      "weight":  {
                        "type": ["number","null"]
                      },
                      "aboRh":  {
                        "type": "string"
                      },
                      "donationDate":  {
                        "type": "string"
                      },
                      "drawBeginTime":  {
                        "type": ["string","null"]
                      },
                      "collectionFacility":  {
                        "type": "string"
                      },
                      "collectionTimeZone":  {
                        "type": "string"
                      }
                      },
                      "required": [
                        "unitNumber",
                        "productCode",
                        "packedByEmployeeId",
                        "productType",
                        "aboRh",
                        "donationDate",
                        "collectionFacility",
                        "collectionTimeZone"
                      ]
                    }
                  ]
                }
              },
              "required": [
                "cartonNumber",
                "locationCode",
                "cartonSequence",
                "closeEmployeeId",
                "closeDate",
                "productType",
                "status",
                "totalProducts",
                "packedProducts"
              ]
            }
          ]
        }
     },
      "required": [
        "shipmentNumber",
        "locationCode",
        "status",
        "createEmployeeId",
        "productType",
        "closedEmployeeId",
        "closeDate",
        "customerCode",
        "totalCartons",
        "locationShipmentCode",
        "locationCartonCode",
        "cartonList"
      ]
    }
  },
  "required": [
    "eventId",
    "occurredOn",
    "eventVersion",
    "eventType"
  ]
}

=== mjones3/interface-exception-collector-service/backend/eventbridge/src/test/resources/rps-shipment-closed-event-automation-optional_fields.json
{
  "eventId": "a6a81146-9961-472e-9af8-a4ee9feeb5bc",
  "occurredOn": "2025-05-30T17:08:53.072788037Z",
  "eventType": "RecoveredPlasmaShipmentClosed",
  "eventVersion": "1.0",
  "payload": {
    "locationCode": "123456789",
    "productType": "RP_NONINJECTABLE_LIQUID_RT",
    "shipmentNumber": "{shipmentNumber}",
    "status": "CLOSED",
    "createEmployeeId": "18e41e7a-d06b-47ea-9dc0-3a89ede96bad",
    "transportationReferenceNumber": "DIS-398",
    "shipmentDate": null,
    "cartonTareWeight": 10,
    "createDate": "2025-05-30T17:05:51.916651Z",
    "modificationDate": "2025-05-30T17:08:53.034622Z",
    "closedEmployeeId": "18e41e7a-d06b-47ea-9dc0-3a89ede96bad",
    "closeDate": "2025-05-30T17:08:53.034622Z",
    "customerCode": "409",
    "customerName": "Southern Biologics",
    "customerState": "FL",
    "customerPostalCode": "32303",
    "customerCountry": "USA",
    "customerCountryCode": "USA",
    "customerCity": "Tallahassee",
    "customerDistrict": "",
    "customerAddressLine1": "4801 Woodlane Circle",
    "customerAddressLine2": "Unit 105",
    "customerAddressContactName": null,
    "customerAddressPhoneNumber": null,
    "customerAddressDepartmentName": null,
    "totalCartons": 1,
    "locationShipmentCode": "2765",
    "locationCartonCode": "MH1",
    "cartonList": [
      {
        "cartonNumber": "BPMMH11028",
        "locationCode": "123456789",
        "cartonSequence": 1,
        "closeEmployeeId": "18e41e7a-d06b-47ea-9dc0-3a89ede96bad",
        "closeDate": "2025-05-30T17:06:35.691463Z",
        "productType": "RP_NONINJECTABLE_LIQUID_RT",
        "status": "CLOSED",
        "totalProducts": 1,
        "totalWeight": 0,
        "totalVolume": 0,
        "packedProducts": [
          {
            "unitNumber": "W036825240872",
            "productCode": "E2488V00",
            "packedByEmployeeId": "18e41e7a-d06b-47ea-9dc0-3a89ede96bad",
            "productType": "RP_NONINJECTABLE_LIQUID_RT",
            "volume": 508,
            "weight": 550,
            "aboRh": "AP",
            "donationDate": "2025-05-30T14:54:46.234Z",
            "drawBeginTime": null,
            "collectionFacility": "1FS",
            "collectionTimeZone": "America/New_York"
          }
        ]
      }
    ]
  }
}
